# 1/14 Update
# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: lily58_left nice_view_adapter nice_view
# shield: lily58_right nice_view_adapter nice_view
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# 1/7/2024 zmk
# 2/1/2024 zmk refresh
# 2/19/2024 zmk refresh
# 4/19/2024 zmk 3.5 refresh
# 5/27/2024 zmk refresh
# 9/18/2024 zmk refresh
# 10/22/2024 zmk refresh
# 12/19/2024 zmk refresh
# 3/4/2025 zmk refresh
# 4/17/2025 zmk refresh
# 7/14/2025 zmk refresh and studio
---
include:
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view # nice_view_gem  # old was
    snippet: studio-rpc-usb-uart  # ZMK Studio
    cmake-args: -DCONFIG_ZMK_STUDIO=y # ZMK Studio
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view # nice_view_gem  # old was nice_view
